import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;

  AppLocalizations(this.locale);

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations)!;
  }

  static const LocalizationsDelegate<AppLocalizations> delegate = _AppLocalizationsDelegate();

  static final Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'welcome_back': 'Welcome Back',
      'sign_in_to_continue': 'Sign in to continue',
      'your_home_awaits': 'Your Home Awaits',
      'phone_number': 'Phone Number',
      'password': 'Password',
      'enter_your_password': 'Enter your password',
      'login': 'Login',
      'register': 'Register',
      'phone_required': 'Phone number is required',
      'phone_invalid': 'Please enter a valid Syrian phone number',
      'password_required': 'Password is required',
      'login_error': 'Login Error',
      'ok': 'OK',
      'create_account': 'Create Account',
      'join_us_today': 'Join us today',
      'first_name': 'First Name',
      'last_name': 'Last Name',
      'confirm_password': 'Confirm Password',
      'select_role': 'Select Role',
      'tenant': 'Tenant',
      'landlord': 'Landlord',
      'first_name_required': 'First name is required',
      'last_name_required': 'Last name is required',
      'passwords_not_match': 'Passwords do not match',
      'role_required': 'Please select a role',
      'home': 'Home',
      'favorites': 'Favorites',
      'bookings': 'Bookings',
      'profile': 'Profile',
      'add': 'Add',
      'settings': 'Settings',
      'language': 'Language',
      'theme': 'Theme',
      'dark_mode': 'Dark Mode',
      'light_mode': 'Light Mode',
      'logout': 'Logout',
      'account': 'Account',
      'notifications': 'Notifications',
      'search': 'Search',
      'filter': 'Filter',
      'apply': 'Apply',
      'cancel': 'Cancel',
      'save': 'Save',
      'delete': 'Delete',
      'edit': 'Edit',
      'back': 'Back',
      'next': 'Next',
      'done': 'Done',
      'loading': 'Loading...',
      'error': 'Error',
      'success': 'Success',
      'confirm': 'Confirm',
      'yes': 'Yes',
      'no': 'No',
      'no_internet': 'No internet connection',
      'my_bookings': 'My Bookings',
      'my_favorites': 'My Favorites',
      'add_apartment': 'Add Apartment',
      'apartment_details': 'Apartment Details',
      'price': 'Price',
      'location': 'Location',
      'bedrooms': 'Bedrooms',
      'bathrooms': 'Bathrooms',
      'area': 'Area',
      'description': 'Description',
      'amenities': 'Amenities',
      'available': 'Available',
      'unavailable': 'Unavailable',
      'book_now': 'Book Now',
      'contact_owner': 'Contact Owner',
      'view_details': 'View Details',
      'no_results': 'No results found',
      'try_different_search': 'Try a different search',
      'status': 'Status',
      'pending': 'Pending',
      'approved': 'Approved',
      'rejected': 'Rejected',
      'date': 'Date',
      'time': 'Time',
      'total': 'Total',
      'payment': 'Payment',
      'details': 'Details',
      'received': 'Received',
      'sent': 'Sent',
      'requests': 'Requests',
      'applications': 'Applications',
      'rental_applications': 'Rental Applications',
      'incoming_requests': 'Incoming Requests',
      'my_applications': 'My Applications',
      'apartments_found': 'Apartments Found',
      'apartment': 'Apartment',
      'apartments': 'Apartments',
      'title': 'Title',
      'address': 'Address',
      'city': 'City',
      'state': 'State',
      'zip_code': 'Zip Code',
      'rent_price': 'Rent Price',
      'deposit': 'Deposit',
      'lease_duration': 'Lease Duration',
      'move_in_date': 'Move In Date',
      'furnished': 'Furnished',
      'unfurnished': 'Unfurnished',
      'parking': 'Parking',
      'pets_allowed': 'Pets Allowed',
      'utilities_included': 'Utilities Included',
      'photos': 'Photos',
      'upload_photos': 'Upload Photos',
      'submit': 'Submit',
      'update': 'Update',
      'remove': 'Remove',
      'view': 'View',
      'close': 'Close',
      'open': 'Open',
      'active': 'Active',
      'inactive': 'Inactive',
      'completed': 'Completed',
      'cancelled': 'Cancelled',
      'confirmed': 'Confirmed',
      'booking_details': 'Booking Details',
      'booking_date': 'Booking Date',
      'check_in': 'Check In',
      'check_out': 'Check Out',
      'guest_name': 'Guest Name',
      'owner_name': 'Owner Name',
      'contact_info': 'Contact Information',
      'email': 'Email',
      'message': 'Message',
      'send_message': 'Send Message',
      'no_bookings': 'No bookings yet',
      'no_favorites': 'No favorites yet',
      'no_apartments': 'No apartments found',
      'add_to_favorites': 'Add to Favorites',
      'remove_from_favorites': 'Remove from Favorites',
      'share': 'Share',
      'report': 'Report',
      'reviews': 'Reviews',
      'rating': 'Rating',
      'write_review': 'Write a Review',
      'sort_by': 'Sort By',
      'price_low_high': 'Price: Low to High',
      'price_high_low': 'Price: High to Low',
      'newest_first': 'Newest First',
      'oldest_first': 'Oldest First',
      'filters': 'Filters',
      'clear_filters': 'Clear Filters',
      'min_price': 'Min Price',
      'max_price': 'Max Price',
      'property_type': 'Property Type',
      'all': 'All',
      'theme_mode': 'Theme Mode',
      'help_support': 'Help & Support',
      'not_logged_in': 'Not Logged In',
      'please_login': 'Please login to view your profile',
      'go_to_login': 'Go to Login',
      'night': 'night',
      'beds': 'Beds',
      'baths': 'Baths',
      'no_description': 'No description available',
      'features_amenities': 'Features & Amenities',
      'apartment_not_found': 'Apartment not found',
      'removed_from_favorites': 'Removed from favorites',
      'added_to_favorites': 'Added to favorites',
      'book_now': 'Book Now',
      'edit_apartment': 'Edit Apartment',
      'login_required': 'Login Required',
      'please_login_to_book': 'Please login to book this apartment',
      'city': 'City',
      'governorate': 'Governorate',
      'address': 'Address',
      'property_owner': 'Property Owner',
      'booking_sent_success': 'Booking request sent successfully!',
      'apartment_updated_success': 'Apartment updated successfully!',
      'help_support': 'Help & Support',
      'logout': 'Logout',
      'language': 'Language',
      'theme_mode': 'Theme Mode',
      'available_only': 'Available Only',
      'booked': 'Booked',
    },
    'ar': {
      'welcome_back': 'مرحباً بعودتك',
      'sign_in_to_continue': 'سجل الدخول للمتابعة',
      'your_home_awaits': 'منزلك بانتظارك',
      'phone_number': 'رقم الهاتف',
      'password': 'كلمة المرور',
      'enter_your_password': 'أدخل كلمة المرور',
      'login': 'تسجيل الدخول',
      'register': 'تسجيل',
      'phone_required': 'رقم الهاتف مطلوب',
      'phone_invalid': 'الرجاء إدخال رقم هاتف سوري صحيح',
      'password_required': 'كلمة المرور مطلوبة',
      'login_error': 'خطأ في تسجيل الدخول',
      'ok': 'حسناً',
      'create_account': 'إنشاء حساب',
      'join_us_today': 'انضم إلينا اليوم',
      'first_name': 'الاسم الأول',
      'last_name': 'الاسم الأخير',
      'confirm_password': 'تأكيد كلمة المرور',
      'select_role': 'اختر الدور',
      'tenant': 'مستأجر',
      'landlord': 'مالك',
      'first_name_required': 'الاسم الأول مطلوب',
      'last_name_required': 'الاسم الأخير مطلوب',
      'passwords_not_match': 'كلمات المرور غير متطابقة',
      'role_required': 'الرجاء اختيار الدور',
      'home': 'الرئيسية',
      'favorites': 'المفضلة',
      'bookings': 'الحجوزات',
      'profile': 'الملف الشخصي',
      'add': 'إضافة',
      'settings': 'الإعدادات',
      'language': 'اللغة',
      'theme': 'المظهر',
      'dark_mode': 'الوضع الداكن',
      'light_mode': 'الوضع الفاتح',
      'logout': 'تسجيل الخروج',
      'account': 'الحساب',
      'notifications': 'الإشعارات',
      'search': 'بحث',
      'filter': 'تصفية',
      'apply': 'تطبيق',
      'cancel': 'إلغاء',
      'save': 'حفظ',
      'delete': 'حذف',
      'edit': 'تعديل',
      'back': 'رجوع',
      'next': 'التالي',
      'done': 'تم',
      'loading': 'جاري التحميل...',
      'error': 'خطأ',
      'success': 'نجح',
      'confirm': 'تأكيد',
      'yes': 'نعم',
      'no': 'لا',
      'no_internet': 'لا يوجد اتصال بالإنترنت',
      'my_bookings': 'حجوزاتي',
      'my_favorites': 'مفضلاتي',
      'add_apartment': 'إضافة شقة',
      'apartment_details': 'تفاصيل الشقة',
      'price': 'السعر',
      'location': 'الموقع',
      'bedrooms': 'غرف النوم',
      'bathrooms': 'الحمامات',
      'area': 'المساحة',
      'description': 'الوصف',
      'amenities': 'المرافق',
      'available': 'متاح',
      'unavailable': 'غير متاح',
      'book_now': 'احجز الآن',
      'contact_owner': 'اتصل بالمالك',
      'view_details': 'عرض التفاصيل',
      'no_results': 'لا توجد نتائج',
      'try_different_search': 'جرب بحثاً مختلفاً',
      'status': 'الحالة',
      'pending': 'قيد الانتظار',
      'approved': 'موافق عليه',
      'rejected': 'مرفوض',
      'date': 'التاريخ',
      'time': 'الوقت',
      'total': 'المجموع',
      'payment': 'الدفع',
      'details': 'التفاصيل',
      'received': 'المستلمة',
      'sent': 'المرسلة',
      'requests': 'الطلبات',
      'applications': 'التطبيقات',
      'rental_applications': 'طلبات الإيجار',
      'incoming_requests': 'الطلبات الواردة',
      'my_applications': 'طلباتي',
      'apartments_found': 'شقة متاحة',
      'apartment': 'شقة',
      'apartments': 'شقق',
      'title': 'العنوان',
      'address': 'العنوان',
      'city': 'المدينة',
      'state': 'المحافظة',
      'zip_code': 'الرمز البريدي',
      'rent_price': 'سعر الإيجار',
      'deposit': 'التأمين',
      'lease_duration': 'مدة الإيجار',
      'move_in_date': 'تاريخ الانتقال',
      'furnished': 'مفروشة',
      'unfurnished': 'غير مفروشة',
      'parking': 'موقف سيارات',
      'pets_allowed': 'يسمح بالحيوانات',
      'utilities_included': 'المرافق مشمولة',
      'photos': 'الصور',
      'upload_photos': 'رفع الصور',
      'submit': 'إرسال',
      'update': 'تحديث',
      'remove': 'إزالة',
      'view': 'عرض',
      'close': 'إغلاق',
      'open': 'فتح',
      'active': 'نشط',
      'inactive': 'غير نشط',
      'completed': 'مكتمل',
      'cancelled': 'ملغى',
      'confirmed': 'مؤكد',
      'booking_details': 'تفاصيل الحجز',
      'booking_date': 'تاريخ الحجز',
      'check_in': 'تسجيل الدخول',
      'check_out': 'تسجيل الخروج',
      'guest_name': 'اسم الضيف',
      'owner_name': 'اسم المالك',
      'contact_info': 'معلومات الاتصال',
      'email': 'البريد الإلكتروني',
      'message': 'رسالة',
      'send_message': 'إرسال رسالة',
      'no_bookings': 'لا توجد حجوزات بعد',
      'no_favorites': 'لا توجد مفضلات بعد',
      'no_apartments': 'لم يتم العثور على شقق',
      'add_to_favorites': 'إضافة للمفضلة',
      'remove_from_favorites': 'إزالة من المفضلة',
      'share': 'مشاركة',
      'report': 'إبلاغ',
      'reviews': 'التقييمات',
      'rating': 'التقييم',
      'write_review': 'كتابة تقييم',
      'sort_by': 'ترتيب حسب',
      'price_low_high': 'السعر: من الأقل للأعلى',
      'price_high_low': 'السعر: من الأعلى للأقل',
      'newest_first': 'الأحدث أولاً',
      'oldest_first': 'الأقدم أولاً',
      'filters': 'الفلاتر',
      'clear_filters': 'مسح الفلاتر',
      'min_price': 'أقل سعر',
      'max_price': 'أعلى سعر',
      'property_type': 'نوع العقار',
      'all': 'الكل',
      'theme_mode': 'وضع المظهر',
      'help_support': 'المساعدة والدعم',
      'not_logged_in': 'غير مسجل الدخول',
      'please_login': 'الرجاء تسجيل الدخول لعرض ملفك الشخصي',
      'go_to_login': 'الذهاب لتسجيل الدخول',
      'night': 'ليلة',
      'beds': 'أسرّة',
      'baths': 'حمامات',
      'no_description': 'لا يوجد وصف متاح',
      'features_amenities': 'المميزات والمرافق',
      'apartment_not_found': 'الشقة غير موجودة',
      'removed_from_favorites': 'تمت الإزالة من المفضلة',
      'added_to_favorites': 'تمت الإضافة للمفضلة',
      'book_now': 'احجز الآن',
      'edit_apartment': 'تعديل الشقة',
      'login_required': 'تسجيل الدخول مطلوب',
      'please_login_to_book': 'الرجاء تسجيل الدخول لحجز هذه الشقة',
      'city': 'المدينة',
      'governorate': 'المحافظة',
      'address': 'العنوان',
      'property_owner': 'مالك العقار',
      'booking_sent_success': 'تم إرسال طلب الحجز بنجاح!',
      'apartment_updated_success': 'تم تحديث الشقة بنجاح!',
      'help_support': 'المساعدة والدعم',
      'logout': 'تسجيل الخروج',
      'language': 'اللغة',
      'theme_mode': 'وضع المظهر',
      'available_only': 'المتاح فقط',
      'booked': 'محجوز',
    },
  };

  String translate(String key) => _localizedValues[locale.languageCode]?[key] ?? key;
}

class _AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => ['en', 'ar'].contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) async => AppLocalizations(locale);

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}
