import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;

  AppLocalizations(this.locale);

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations)!;
  }

  static const LocalizationsDelegate<AppLocalizations> delegate =
      _AppLocalizationsDelegate();

  static final Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'welcome_back': 'Welcome Back',
      'sign_in_to_continue': 'Sign in to continue',
      'your_home_awaits': 'Your Home Awaits',
      'phone_number': 'Phone Number',
      'password': 'Password',
      'enter_your_password': 'Enter your password',
      'login': 'Login',
      'register': 'Register',
      'phone_required': 'Phone number is required',
      'phone_invalid': 'Please enter a valid Syrian phone number',
      'password_required': 'Password is required',
      'login_error': 'Login Error',
      'ok': 'OK',
      'create_account': 'Create Account',
      'join_us_today': 'Join us today',
      'first_name': 'First Name',
      'last_name': 'Last Name',
      'confirm_password': 'Confirm Password',
      'select_role': 'Select Role',
      'tenant': 'Tenant',
      'landlord': 'Landlord',
      'first_name_required': 'First name is required',
      'last_name_required': 'Last name is required',
      'passwords_not_match': 'Passwords do not match',
      'role_required': 'Please select a role',
      'home': 'Home',
      'favorites': 'Favorites',
      'bookings': 'Bookings',
      'profile': 'Profile',
      'add': 'Add',
      'settings': 'Settings',
      'language': 'Language',
      'theme': 'Theme',
      'dark_mode': 'Dark Mode',
      'light_mode': 'Light Mode',
      'logout': 'Logout',
      'account': 'Account',
      'notifications': 'Notifications',
      'search': 'Search',
      'filter': 'Filter',
      'apply': 'Apply',
      'cancel': 'Cancel',
      'save': 'Save',
      'delete': 'Delete',
      'edit': 'Edit',
      'back': 'Back',
      'next': 'Next',
      'done': 'Done',
      'loading': 'Loading...',
      'error': 'Error',
      'success': 'Success',
      'confirm': 'Confirm',
      'yes': 'Yes',
      'no': 'No',
      'no_internet': 'No internet connection',
      'my_bookings': 'My Bookings',
      'my_favorites': 'My Favorites',
      'add_apartment': 'Add Apartment',
      'apartment_details': 'Apartment Details',
      'price': 'Price',
      'location': 'Location',
      'bedrooms': 'Bedrooms',
      'bathrooms': 'Bathrooms',
      'area': 'Area',
      'description': 'Description',
      'amenities': 'Amenities',
      'available': 'Available',
      'unavailable': 'Unavailable',
      'book_now': 'Book Now',
      'contact_owner': 'Contact Owner',
      'view_details': 'View Details',
      'no_results': 'No results found',
      'try_different_search': 'Try a different search',
      'status': 'Status',
      'pending': 'Pending',
      'approved': 'Approved',
      'rejected': 'Rejected',
      'date': 'Date',
      'time': 'Time',
      'total': 'Total',
      'payment': 'Payment',
      'details': 'Details',
      'received': 'Received',
      'sent': 'Sent',
      'requests': 'Requests',
      'applications': 'Applications',
      'rental_applications': 'Rental Applications',
      'incoming_requests': 'Incoming Requests',
      'my_applications': 'My Applications',
      'apartments_found': 'Apartments Found',
      'apartment': 'Apartment',
      'apartments': 'Apartments',
      'title': 'Title',
      'address': 'Address',
      'city': 'City',
      'state': 'State',
      'zip_code': 'Zip Code',
      'rent_price': 'Rent Price',
      'deposit': 'Deposit',
      'lease_duration': 'Lease Duration',
      'move_in_date': 'Move In Date',
      'furnished': 'Furnished',
      'unfurnished': 'Unfurnished',
      'parking': 'Parking',
      'pets_allowed': 'Pets Allowed',
      'utilities_included': 'Utilities Included',
      'photos': 'Photos',
      'upload_photos': 'Upload Photos',
      'submit': 'Submit',
      'update': 'Update',
      'remove': 'Remove',
      'view': 'View',
      'close': 'Close',
      'open': 'Open',
      'active': 'Active',
      'inactive': 'Inactive',
      'completed': 'Completed',
      'cancelled': 'Cancelled',
      'confirmed': 'Confirmed',
      'booking_details': 'Booking Details',
      'booking_date': 'Booking Date',
      'check_in': 'Check In',
      'check_out': 'Check Out',
      'guest_name': 'Guest Name',
      'owner_name': 'Owner Name',
      'contact_info': 'Contact Information',
      'email': 'Email',
      'message': 'Message',
      'send_message': 'Send Message',
      'no_bookings': 'No bookings yet',
      'no_favorites': 'No favorites yet',
      'no_apartments': 'No apartments found',
      'add_to_favorites': 'Add to Favorites',
      'remove_from_favorites': 'Remove from Favorites',
      'share': 'Share',
      'report': 'Report',
      'reviews': 'Reviews',
      'rating': 'Rating',
      'write_review': 'Write a Review',
      'sort_by': 'Sort By',
      'price_low_high': 'Price: Low to High',
      'price_high_low': 'Price: High to Low',
      'newest_first': 'Newest First',
      'oldest_first': 'Oldest First',
      'filters': 'Filters',
      'clear_filters': 'Clear Filters',
      'min_price': 'Min Price',
      'max_price': 'Max Price',
      'property_type': 'Property Type',
      'all': 'All',
      'theme_mode': 'Theme Mode',
      'help_support': 'Help & Support',
      'not_logged_in': 'Not Logged In',
      'please_login': 'Please login to view your profile',
      'go_to_login': 'Go to Login',
      'night': 'night',
      'beds': 'Beds',
      'baths': 'Baths',
      'no_description': 'No description available',
      'features_amenities': 'Features & Amenities',
      'apartment_not_found': 'Apartment not found',
      'removed_from_favorites': 'Removed from favorites',
      'added_to_favorites': 'Added to favorites',
      'book_now': 'Book Now',
      'edit_apartment': 'Edit Apartment',
      'login_required': 'Login Required',
      'please_login_to_book': 'Please login to book this apartment',
      'city': 'City',
      'governorate': 'Governorate',
      'address': 'Address',
      'property_owner': 'Property Owner',
      'booking_sent_success': 'Booking request sent successfully!',
      'apartment_updated_success': 'Apartment updated successfully!',
      'help_support': 'Help & Support',
      'logout': 'Logout',
      'language': 'Language',
      'theme_mode': 'Theme Mode',
      'available_only': 'Available Only',
      'booked': 'Booked',
      'add_apartment': 'Add Apartment',
      'edit_apartment': 'Edit Apartment',
      'create_listing': 'Create your apartment listing',
      'update_details': 'Update your apartment details',
      'basic_information': 'Basic Information',
      'title': 'Title',
      'title_required': 'Title is required',
      'title_min_length': 'Title must be at least 3 characters',
      'description': 'Description',
      'description_required': 'Description is required',
      'description_min_length': 'Description must be at least 10 characters',
      'location': 'Location',
      'governorate': 'Governorate',
      'select_governorate': 'Please select governorate',
      'city': 'City',
      'select_city': 'Please select city',
      'details': 'Details',
      'price_per_night': 'Price per Night (\$)',
      'enter_price': 'Enter price per night',
      'price_required': 'Price is required',
      'valid_price': 'Enter a valid price',
      'max_guests': 'Max Guests',
      'rooms': 'Rooms',
      'bedrooms': 'Bedrooms',
      'bathrooms': 'Bathrooms',
      'required': 'Required',
      'invalid': 'Invalid',
      'area_m2': 'Area (m²)',
      'enter_area': 'Enter area in square meters',
      'area_required': 'Area is required',
      'valid_area': 'Enter a valid area',
      'features_amenities': 'Features & Amenities',
      'loading_features': 'Loading features...',
      'images': 'Images',
      'add_photos': 'Add Photos',
      'select_multiple': 'Select multiple images at once',
      'photos': 'Photo',
      'add_more': 'Add More',
      'cover': 'Cover',
      'submit_apartment': 'Submit Apartment',
      'update_apartment': 'Update Apartment',
      'success': 'Success!',
      'apartment_created':
          'Your apartment has been created successfully and is now live!',
      'apartment_updated': 'Your apartment has been updated successfully!',
      'select_governorate_city': 'Please select governorate and city',
      'select_one_image': 'Please select at least one image',
      'keep_one_image': 'Please keep at least one image or add new images',
      'failed_add': 'Failed to add apartment',
      'failed_update': 'Failed to update apartment',
      'failed_load_features': 'Failed to load available features',
      'wifi': 'WiFi',
      'air_conditioning': 'Air Conditioning',
      'heating': 'Heating',
      'kitchen': 'Kitchen',
      'washer': 'Washer',
      'tv': 'TV',
      'parking': 'Parking',
      'elevator': 'Elevator',
      'balcony': 'Balcony',
      'gym': 'Gym',
      'pool': 'Pool',
      'security': 'Security',
      'garden': 'Garden',
      'furnished': 'Furnished',
      'pet_friendly': 'Pet Friendly',
      'damascus': 'Damascus',
      'aleppo': 'Aleppo',
      'homs': 'Homs',
      'hama': 'Hama',
      'latakia': 'Latakia',
      'tartus': 'Tartus',
      'idlib': 'Idlib',
      'daraa': 'Daraa',
      'deir_ez_zor': 'Deir ez-Zor',
      'raqqa': 'Raqqa',
      'al_hasakah': 'Al-Hasakah',
      'quneitra': 'Quneitra',
      'as_suwayda': 'As-Suwayda',
      'jaramana': 'Jaramana',
      'sahnaya': 'Sahnaya',
      'afrin': 'Afrin',
      'al_bab': 'Al-Bab',
      'palmyra': 'Palmyra',
      'qusayr': 'Qusayr',
      'salamiyah': 'Salamiyah',
      'suqaylabiyah': 'Suqaylabiyah',
      'jableh': 'Jableh',
      'qardaha': 'Qardaha',
      'banias': 'Banias',
      'safita': 'Safita',
      'washing_machine': 'Washing Machine',
      'swimming_pool': 'Swimming Pool',
      'terrace': 'Terrace',
      'my_requests': 'My Requests',
      'no_bookings_yet': 'No bookings yet',
      'no_received_bookings': 'No received bookings',
      'upcoming_on_apartments': 'Upcoming on My Apartments',
      'my_pending': 'My Pending',
      'my_ongoing': 'My Ongoing',
      'my_cancelled_rejected': 'Cancelled/Rejected',
      'my_expired': 'Expired',
      'time_remaining': 'Time Remaining',
      'contract_starts_in': 'Contract Starts In',
      'no_upcoming_bookings': 'No upcoming bookings on your apartments',
      'no_pending_bookings': 'No pending bookings',
      'no_ongoing_bookings': 'No ongoing bookings',
      'no_cancelled_rejected_bookings': 'No cancelled or rejected bookings',
      'no_expired_bookings': 'No expired bookings',
      'error_loading_bookings': 'Error loading bookings',
      'unknown_error': 'Unknown error',
      'retry': 'Retry',
      'duration': 'Duration',
      'nights': 'nights',
      'total_amount': 'Total amount',
      'approve': 'Approve',
      'reject': 'Reject',
      'approve_booking': 'Approve Booking',
      'are_you_sure_approve': 'Are you sure you want to approve this booking?',
      'amount': 'Amount',
      'payment_transfer_message':
          'The payment will be automatically transferred from the tenant\'s wallet to your wallet.',
      'approve_process_payment': 'Approve & Process Payment',
      'booking_approved_success':
          'Booking approved and payment processed successfully!',
      'failed_approve_booking': 'Failed to approve booking',
      'reject_booking': 'Reject Booking',
      'are_you_sure_reject': 'Are you sure you want to reject this booking for',
      'booking_rejected_success': 'Booking rejected successfully!',
      'failed_reject_booking': 'Failed to reject booking',
      'edit_booking_dates': 'Edit Booking Dates',
      'submit_modification': 'Submit Modification',
      'modification_submitted_success': 'Modification submitted successfully!',
      'failed_submit_modification': 'Failed to submit modification',
      'check_in_date': 'Check-in Date',
      'check_out_date': 'Check-out Date',
      'booking_updated_success': 'Booking updated successfully!',
      'failed_update_booking': 'Failed to update booking',
      'delete_booking': 'Delete Booking',
      'are_you_sure_delete': 'Are you sure you want to delete this booking for',
      'booking_deleted_success': 'Booking deleted successfully!',
      'my_bookings': 'My Bookings',
      'wallet': 'Wallet',
      'my_wallet': 'My Wallet',
      'total_balance': 'Total Balance',
      'deposit': 'Deposit',
      'withdraw': 'Withdraw',
      'recent_transactions': 'Recent Transactions',
      'view_all': 'View All',
      'no_transactions_yet': 'No transactions yet',
      'my_requests': 'My Requests',
      'refresh': 'Refresh',
      'no_requests_yet': 'No requests yet',
      'error_loading_wallet': 'Error loading wallet',
      'no_wallet_found': 'No wallet found',
      'rental_payment': 'Rental Payment',
      'rental_received': 'Rental Received',
      'withdrawal': 'Withdrawal',
      'deposit_request': 'Deposit Request',
      'deposit_request': 'Deposit Request',
      'withdrawal_request': 'Withdrawal Request',
      'deposit_money': 'Deposit Money',
      'enter_deposit_info':
          'Enter the amount you want to deposit. Your request will be reviewed by admin.',
      'amount_usd': 'Amount (USD)',
      'enter_amount_usd': 'Enter amount in USD',
      'please_enter_amount': 'Please enter an amount',
      'enter_valid_amount': 'Please enter a valid amount greater than 0',
      'equivalent_in_spy': 'Equivalent in SPY',
      'submit_deposit_request': 'Submit Deposit Request',
      'deposit_request_success': 'Deposit request submitted successfully!',
      'failed_submit_deposit': 'Failed to submit deposit request',
      'transaction_history': 'Transaction History',
      'error_loading_transactions': 'Error loading transactions',
      'no_transactions_found': 'No transactions found',
      'start_adding_favorites': 'Start adding apartments to your favorites',
      'no_match_filters': 'No apartments match your filters',
      'newest': 'Newest First',
      'oldest': 'Oldest First',
      'price_low': 'Price: Low to High',
      'price_high': 'Price: High to Low',
      'area_small': 'Area: Small to Large',
      'area_large': 'Area: Large to Small',
      'price_range': 'Price Range',
      'sort_by': 'Sort By',
    },
    'ar': {
      'welcome_back': 'مرحباً بعودتك',
      'sign_in_to_continue': 'سجل الدخول للمتابعة',
      'your_home_awaits': 'منزلك بانتظارك',
      'phone_number': 'رقم الهاتف',
      'password': 'كلمة المرور',
      'enter_your_password': 'أدخل كلمة المرور',
      'login': 'تسجيل الدخول',
      'register': 'تسجيل',
      'phone_required': 'رقم الهاتف مطلوب',
      'phone_invalid': 'الرجاء إدخال رقم هاتف سوري صحيح',
      'password_required': 'كلمة المرور مطلوبة',
      'login_error': 'خطأ في تسجيل الدخول',
      'ok': 'حسناً',
      'create_account': 'إنشاء حساب',
      'join_us_today': 'انضم إلينا اليوم',
      'first_name': 'الاسم الأول',
      'last_name': 'الاسم الأخير',
      'confirm_password': 'تأكيد كلمة المرور',
      'select_role': 'اختر الدور',
      'tenant': 'مستأجر',
      'landlord': 'مالك',
      'first_name_required': 'الاسم الأول مطلوب',
      'last_name_required': 'الاسم الأخير مطلوب',
      'passwords_not_match': 'كلمات المرور غير متطابقة',
      'role_required': 'الرجاء اختيار الدور',
      'home': 'الرئيسية',
      'favorites': 'المفضلة',
      'bookings': 'الحجوزات',
      'profile': 'الملف الشخصي',
      'add': 'إضافة',
      'settings': 'الإعدادات',
      'language': 'اللغة',
      'theme': 'المظهر',
      'dark_mode': 'الوضع الداكن',
      'light_mode': 'الوضع الفاتح',
      'logout': 'تسجيل الخروج',
      'account': 'الحساب',
      'notifications': 'الإشعارات',
      'search': 'بحث',
      'filter': 'تصفية',
      'apply': 'تطبيق',
      'cancel': 'إلغاء',
      'save': 'حفظ',
      'delete': 'حذف',
      'edit': 'تعديل',
      'back': 'رجوع',
      'next': 'التالي',
      'done': 'تم',
      'loading': 'جاري التحميل...',
      'error': 'خطأ',
      'success': 'نجح',
      'confirm': 'تأكيد',
      'yes': 'نعم',
      'no': 'لا',
      'no_internet': 'لا يوجد اتصال بالإنترنت',
      'my_bookings': 'حجوزاتي',
      'my_favorites': 'مفضلاتي',
      'add_apartment': 'إضافة شقة',
      'apartment_details': 'تفاصيل الشقة',
      'price': 'السعر',
      'location': 'الموقع',
      'bedrooms': 'غرف النوم',
      'bathrooms': 'الحمامات',
      'area': 'المساحة',
      'description': 'الوصف',
      'amenities': 'المرافق',
      'available': 'متاح',
      'unavailable': 'غير متاح',
      'book_now': 'احجز الآن',
      'contact_owner': 'اتصل بالمالك',
      'view_details': 'عرض التفاصيل',
      'no_results': 'لا توجد نتائج',
      'try_different_search': 'جرب بحثاً مختلفاً',
      'status': 'الحالة',
      'pending': 'قيد الانتظار',
      'approved': 'موافق عليه',
      'rejected': 'مرفوض',
      'date': 'التاريخ',
      'time': 'الوقت',
      'total': 'المجموع',
      'payment': 'الدفع',
      'details': 'التفاصيل',
      'received': 'المستلمة',
      'sent': 'المرسلة',
      'requests': 'الطلبات',
      'applications': 'التطبيقات',
      'rental_applications': 'طلبات الإيجار',
      'incoming_requests': 'الطلبات الواردة',
      'my_applications': 'طلباتي',
      'apartments_found': 'شقة متاحة',
      'apartment': 'شقة',
      'apartments': 'شقق',
      'title': 'العنوان',
      'address': 'العنوان',
      'city': 'المدينة',
      'state': 'المحافظة',
      'zip_code': 'الرمز البريدي',
      'rent_price': 'سعر الإيجار',
      'deposit': 'التأمين',
      'lease_duration': 'مدة الإيجار',
      'move_in_date': 'تاريخ الانتقال',
      'furnished': 'مفروشة',
      'unfurnished': 'غير مفروشة',
      'parking': 'موقف سيارات',
      'pets_allowed': 'يسمح بالحيوانات',
      'utilities_included': 'المرافق مشمولة',
      'photos': 'الصور',
      'upload_photos': 'رفع الصور',
      'submit': 'إرسال',
      'update': 'تحديث',
      'remove': 'إزالة',
      'view': 'عرض',
      'close': 'إغلاق',
      'open': 'فتح',
      'active': 'نشط',
      'inactive': 'غير نشط',
      'completed': 'مكتمل',
      'cancelled': 'ملغى',
      'confirmed': 'مؤكد',
      'booking_details': 'تفاصيل الحجز',
      'booking_date': 'تاريخ الحجز',
      'check_in': 'تسجيل الدخول',
      'check_out': 'تسجيل الخروج',
      'guest_name': 'اسم الضيف',
      'owner_name': 'اسم المالك',
      'contact_info': 'معلومات الاتصال',
      'email': 'البريد الإلكتروني',
      'message': 'رسالة',
      'send_message': 'إرسال رسالة',
      'no_bookings': 'لا توجد حجوزات بعد',
      'no_favorites': 'لا توجد مفضلات بعد',
      'no_apartments': 'لم يتم العثور على شقق',
      'add_to_favorites': 'إضافة للمفضلة',
      'remove_from_favorites': 'إزالة من المفضلة',
      'share': 'مشاركة',
      'report': 'إبلاغ',
      'reviews': 'التقييمات',
      'rating': 'التقييم',
      'write_review': 'كتابة تقييم',
      'sort_by': 'ترتيب حسب',
      'price_low_high': 'السعر: من الأقل للأعلى',
      'price_high_low': 'السعر: من الأعلى للأقل',
      'newest_first': 'الأحدث أولاً',
      'oldest_first': 'الأقدم أولاً',
      'filters': 'الفلاتر',
      'clear_filters': 'مسح الفلاتر',
      'min_price': 'أقل سعر',
      'max_price': 'أعلى سعر',
      'property_type': 'نوع العقار',
      'all': 'الكل',
      'theme_mode': 'وضع المظهر',
      'help_support': 'المساعدة والدعم',
      'not_logged_in': 'غير مسجل الدخول',
      'please_login': 'الرجاء تسجيل الدخول لعرض ملفك الشخصي',
      'go_to_login': 'الذهاب لتسجيل الدخول',
      'night': 'ليلة',
      'beds': 'أسرّة',
      'baths': 'حمامات',
      'no_description': 'لا يوجد وصف متاح',
      'features_amenities': 'المميزات والمرافق',
      'apartment_not_found': 'الشقة غير موجودة',
      'removed_from_favorites': 'تمت الإزالة من المفضلة',
      'added_to_favorites': 'تمت الإضافة للمفضلة',
      'book_now': 'احجز الآن',
      'edit_apartment': 'تعديل الشقة',
      'login_required': 'تسجيل الدخول مطلوب',
      'please_login_to_book': 'الرجاء تسجيل الدخول لحجز هذه الشقة',
      'city': 'المدينة',
      'governorate': 'المحافظة',
      'address': 'العنوان',
      'property_owner': 'مالك العقار',
      'booking_sent_success': 'تم إرسال طلب الحجز بنجاح!',
      'apartment_updated_success': 'تم تحديث الشقة بنجاح!',
      'help_support': 'المساعدة والدعم',
      'logout': 'تسجيل الخروج',
      'language': 'اللغة',
      'theme_mode': 'وضع المظهر',
      'available_only': 'المتاح فقط',
      'booked': 'محجوز',
      'add_apartment': 'إضافة شقة',
      'edit_apartment': 'تعديل الشقة',
      'create_listing': 'إنشاء إعلان شقتك',
      'update_details': 'تحديث تفاصيل شقتك',
      'basic_information': 'المعلومات الأساسية',
      'title': 'العنوان',
      'title_required': 'العنوان مطلوب',
      'title_min_length': 'يجب أن يكون العنوان 3 أحرف على الأقل',
      'description': 'الوصف',
      'description_required': 'الوصف مطلوب',
      'description_min_length': 'يجب أن يكون الوصف 10 أحرف على الأقل',
      'location': 'الموقع',
      'governorate': 'المحافظة',
      'select_governorate': 'الرجاء اختيار المحافظة',
      'city': 'المدينة',
      'select_city': 'الرجاء اختيار المدينة',
      'details': 'التفاصيل',
      'price_per_night': 'السعر لليلة (\$)',
      'enter_price': 'أدخل السعر لليلة',
      'price_required': 'السعر مطلوب',
      'valid_price': 'أدخل سعراً صحيحاً',
      'max_guests': 'الحد الأقصى للضيوف',
      'rooms': 'الغرف',
      'bedrooms': 'غرف النوم',
      'bathrooms': 'الحمامات',
      'required': 'مطلوب',
      'invalid': 'غير صحيح',
      'area_m2': 'المساحة (م²)',
      'enter_area': 'أدخل المساحة بالمتر المربع',
      'area_required': 'المساحة مطلوبة',
      'valid_area': 'أدخل مساحة صحيحة',
      'features_amenities': 'المميزات والمرافق',
      'loading_features': 'جاري تحميل المميزات...',
      'images': 'الصور',
      'add_photos': 'إضافة صور',
      'select_multiple': 'اختر عدة صور دفعة واحدة',
      'photos': 'صورة',
      'add_more': 'إضافة المزيد',
      'cover': 'الغلاف',
      'submit_apartment': 'إرسال الشقة',
      'update_apartment': 'تحديث الشقة',
      'success': 'نجاح!',
      'apartment_created': 'تم إنشاء شقتك بنجاح وهي الآن متاحة!',
      'apartment_updated': 'تم تحديث شقتك بنجاح!',
      'select_governorate_city': 'الرجاء اختيار المحافظة والمدينة',
      'select_one_image': 'الرجاء اختيار صورة واحدة على الأقل',
      'keep_one_image':
          'الرجاء الاحتفاظ بصورة واحدة على الأقل أو إضافة صور جديدة',
      'failed_add': 'فشل في إضافة الشقة',
      'failed_update': 'فشل في تحديث الشقة',
      'failed_load_features': 'فشل في تحميل المميزات المتاحة',
      'wifi': 'واي فاي',
      'air_conditioning': 'تكييف',
      'heating': 'تدفئة',
      'kitchen': 'مطبخ',
      'washer': 'غسالة',
      'tv': 'تلفزيون',
      'parking': 'موقف سيارات',
      'elevator': 'مصعد',
      'balcony': 'شرفة',
      'gym': 'صالة رياضية',
      'pool': 'مسبح',
      'security': 'أمن',
      'garden': 'حديقة',
      'furnished': 'مفروشة',
      'pet_friendly': 'يسمح بالحيوانات',
      'damascus': 'دمشق',
      'aleppo': 'حلب',
      'homs': 'حمص',
      'hama': 'حماة',
      'latakia': 'اللاذقية',
      'tartus': 'طرطوس',
      'idlib': 'إدلب',
      'daraa': 'درعا',
      'deir_ez_zor': 'دير الزور',
      'raqqa': 'الرقة',
      'al_hasakah': 'الحسكة',
      'quneitra': 'القنيطرة',
      'as_suwayda': 'السويداء',
      'jaramana': 'جرمانا',
      'sahnaya': 'صحنايا',
      'afrin': 'عفرين',
      'al_bab': 'الباب',
      'palmyra': 'تدمر',
      'qusayr': 'القصير',
      'salamiyah': 'سلمية',
      'suqaylabiyah': 'السقيلبية',
      'jableh': 'جبلة',
      'qardaha': 'القرداحة',
      'banias': 'بانياس',
      'safita': 'صافيتا',
      'washing_machine': 'غسالة',
      'swimming_pool': 'مسبح',
      'terrace': 'شرفة علوية',
      'my_requests': 'طلباتي',
      'received': 'المستلمة',
      'no_bookings_yet': 'لا توجد حجوزات بعد',
      'no_received_bookings': 'لا توجد حجوزات مستلمة',
      'upcoming_on_apartments': 'القادمة على شققتي',
      'my_pending': 'قيد الانتظار',
      'my_ongoing': 'الجارية',
      'my_cancelled_rejected': 'ملغاة/مرفوضة',
      'my_expired': 'منتهية الصلاحية',
      'time_remaining': 'الوقت المتبقي',
      'contract_starts_in': 'يبدأ العقد خلال',
      'no_upcoming_bookings': 'لا توجد حجوزات قادمة على شققك',
      'no_pending_bookings': 'لا توجد حجوزات قيد الانتظار',
      'no_ongoing_bookings': 'لا توجد حجوزات جارية',
      'no_cancelled_rejected_bookings': 'لا توجد حجوزات ملغاة أو مرفوضة',
      'no_expired_bookings': 'لا توجد حجوزات منتهية الصلاحية',
      'error_loading_bookings': 'خطأ في تحميل الحجوزات',
      'unknown_error': 'خطأ غير معروف',
      'retry': 'إعادة المحاولة',
      'apartment': 'شقة',
      'check_in': 'تسجيل الدخول',
      'check_out': 'تسجيل الخروج',
      'duration': 'المدة',
      'nights': 'ليالي',
      'price_per_night': 'السعر لليلة',
      'total_amount': 'المبلغ الإجمالي',
      'approve': 'موافقة',
      'reject': 'رفض',
      'edit': 'تعديل',
      'approve_booking': 'الموافقة على الحجز',
      'are_you_sure_approve': 'هل أنت متأكد من الموافقة على هذا الحجز؟',
      'amount': 'المبلغ',
      'payment_transfer_message':
          'سيتم تحويل الدفع تلقائياً من محفظة المستأجر إلى محفظتك.',
      'approve_process_payment': 'الموافقة ومعالجة الدفع',
      'booking_approved_success': 'تمت الموافقة على الحجز ومعالجة الدفع بنجاح!',
      'failed_approve_booking': 'فشل في الموافقة على الحجز',
      'reject_booking': 'رفض الحجز',
      'are_you_sure_reject': 'هل أنت متأكد من رفض هذا الحجز لـ',
      'booking_rejected_success': 'تم رفض الحجز بنجاح!',
      'failed_reject_booking': 'فشل في رفض الحجز',
      'edit_booking_dates': 'تعديل تواريخ الحجز',
      'submit_modification': 'تقديم التعديل',
      'modification_submitted_success': 'تم تقديم التعديل بنجاح!',
      'failed_submit_modification': 'فشل في تقديم التعديل',
      'check_in_date': 'تاريخ تسجيل الدخول',
      'check_out_date': 'تاريخ تسجيل الخروج',
      'save': 'حفظ',
      'booking_updated_success': 'تم تحديث الحجز بنجاح!',
      'failed_update_booking': 'فشل في تحديث الحجز',
      'delete_booking': 'حذف الحجز',
      'are_you_sure_delete': 'هل أنت متأكد من حذف هذا الحجز لـ',
      'booking_deleted_success': 'تم حذف الحجز بنجاح!',
      'failed_delete_booking': 'فشل في حذف الحجز',
      'my_bookings': 'حجوزاتي',
      'wallet': 'المحفظة',
      'my_wallet': 'محفظتي',
      'total_balance': 'الرصيد الإجمالي',
      'deposit': 'إيداع',
      'withdraw': 'سحب',
      'recent_transactions': 'المعاملات الأخيرة',
      'view_all': 'عرض الكل',
      'no_transactions_yet': 'لا توجد معاملات بعد',
      'my_requests': 'طلباتي',
      'refresh': 'تحديث',
      'no_requests_yet': 'لا توجد طلبات بعد',
      'error_loading_wallet': 'خطأ في تحميل المحفظة',
      'no_wallet_found': 'لم يتم العثور على محفظة',
      'rental_payment': 'دفع إيجار',
      'rental_received': 'إيجار مستلم',
      'withdrawal': 'سحب',
      'deposit_request': 'طلب إيداع',
      'withdrawal_request': 'طلب سحب',
      'deposit_money': 'إيداع أموال',
      'enter_deposit_info':
          'أدخل المبلغ الذي تريد إيداعه. سيتم مراجعة طلبك من قبل المسؤول.',
      'amount_usd': 'المبلغ (دولار)',
      'enter_amount_usd': 'أدخل المبلغ بالدولار',
      'please_enter_amount': 'الرجاء إدخال المبلغ',
      'enter_valid_amount': 'الرجاء إدخال مبلغ صحيح أكبر من 0',
      'equivalent_in_spy': 'المعادل بالليرة السورية',
      'submit_deposit_request': 'إرسال طلب الإيداع',
      'deposit_request_success': 'تم إرسال طلب الإيداع بنجاح!',
      'failed_submit_deposit': 'فشل في إرسال طلب الإيداع',
      'transaction_history': 'سجل المعاملات',
      'error_loading_transactions': 'خطأ في تحميل المعاملات',
      'no_transactions_found': 'لم يتم العثور على معاملات',
      'start_adding_favorites': 'ابدأ بإضافة شقق إلى مفضلاتك',
      'no_match_filters': 'لا توجد شقق تطابق الفلاتر',
      'newest': 'الأحدث أولاً',
      'oldest': 'الأقدم أولاً',
      'price_low': 'السعر: من الأقل للأعلى',
      'price_high': 'السعر: من الأعلى للأقل',
      'area_small': 'المساحة: من الأصغر للأكبر',
      'area_large': 'المساحة: من الأكبر للأصغر',
      'price_range': 'نطاق السعر',
      'sort_by': 'ترتيب حسب',
    },
  };

  String translate(String key) =>
      _localizedValues[locale.languageCode]?[key] ?? key;
}

class _AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => ['en', 'ar'].contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) async =>
      AppLocalizations(locale);

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}
